# Generated by Django 3.0.6 on 2020-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=30, unique=True)),
                ('math_subject', models.CharField(max_length=30)),
                ('english_subject', models.CharField(max_length=30)),
                ('kiswahili_subject', models.CharField(max_length=30)),
                ('physics_subject', models.CharField(max_length=30, null=True)),
                ('chemistry_subject', models.CharField(max_length=30, null=True)),
                ('biology_subject', models.CharField(max_length=30, null=True)),
                ('social_studies_subject', models.CharField(max_length=30, null=True)),
                ('geography_subject', models.CharField(max_length=30, null=True)),
                ('history_subject', models.CharField(max_length=30, null=True)),
                ('business_subject', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
