# Generated by Django 3.0.6 on 2020-06-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200606_0742'),
        ('studentsclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='Student',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='term',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], default='DEFAULT', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='biology_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='business_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='chemistry_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='english_subject',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='geography_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='history_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='kiswahili_subject',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='math_subject',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='physics_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='social_studies_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='student_class',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=30),
        ),
    ]
