# Generated by Django 3.0.6 on 2020-06-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsclass', '0003_auto_20200610_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='total_student_marks',
            field=models.IntegerField(default=1),
        ),
    ]
